import image from "./image";
const { food1, food2, food3, food4, food5, food6, food7, food8, food9 } = image;
export const data = {
  pagination: {
    currentPage: 1, // can be dynamically updated
    pageSize: 6,
    total: 30, // total number of vehicles
  },
  vehicles: [
    { id: 1, title: "Cheese Burger", image: food1, price: "₦1,500", review: 4 },
    { id: 2, title: "Beef Burger", image: food9, price: "₦2,500", review: 3 },
    { id: 3, title: "Beef Burger", image: food9, price: "₦2,600", review: 5 },
    { id: 4, title: "Cheese Burger", image: food1, price: "₦1,550", review: 2 },
    { id: 5, title: "Beef Burger", image: food9, price: "₦2,700", review: 4 },
    { id: 6, title: "Cheese Burger", image: food1, price: "₦1,650", review: 3 },
    { id: 7, title: "Cheese Burger", image: food1, price: "₦1,550", review: 5 },
    { id: 8, title: "Beef Burger", image: food9, price: "₦2,750", review: 1 },
    { id: 9, title: "Beef Burger", image: food9, price: "₦2,800", review: 3 },

    {
      id: 10,
      title: "Cheese Burger",
      image: food1,
      price: "₦1,600",
      review: 4,
    },
    {
      id: 11,
      title: "Chips and Burger",
      image: food2,
      price: "₦2,000",
      review: 5,
    },
    {
      id: 12,
      title: "Promo package burger",
      image: food3,
      price: "₦1,800",
      review: 3,
    },
    {
      id: 13,
      title: "Chips and Burger",
      image: food2,
      price: "₦2,100",
      review: 2,
    },
    {
      id: 14,
      title: "Promo package burger",
      image: food3,
      price: "₦1,850",
      review: 4,
    },
    {
      id: 15,
      title: "Promo package burger",
      image: food3,
      price: "₦1,900",
      review: 5,
    },
    {
      id: 16,
      title: "Promo package burger",
      image: food3,
      price: "₦1,950",
      review: 1,
    },
    {
      id: 17,
      title: "Chips and Burger",
      image: food2,
      price: "₦2,050",
      review: 2,
    },
    { id: 18, title: "Beef Burger", image: food9, price: "₦2,850", review: 5 },
    {
      id: 19,
      title: "Cheese Burger",
      image: food1,
      price: "₦1,700",
      review: 3,
    },
    { id: 20, title: "Beef Burger", image: food9, price: "₦2,900", review: 4 },
    { id: 21, title: "Beef Burger", image: food9, price: "₦2,950", review: 2 },
    {
      id: 22,
      title: "Cheese Burger",
      image: food1,
      price: "₦1,750",
      review: 4,
    },
    {
      id: 23,
      title: "Cheese Burger",
      image: food1,
      price: "₦1,800",
      review: 5,
    },
    { id: 24, title: "Beef Burger", image: food9, price: "₦3,000", review: 1 },
    {
      id: 25,
      title: "Cheese Burger",
      image: food1,
      price: "₦1,850",
      review: 3,
    },
    { id: 26, title: "Beef Burger", image: food9, price: "₦3,100", review: 2 },
    {
      id: 27,
      title: "Cheese Burger",
      image: food1,
      price: "₦1,900",
      review: 4,
    },
    {
      id: 28,
      title: "Cheese Burger",
      image: food1,
      price: "₦1,950",
      review: 5,
    },
    { id: 29, title: "Beef Burger", image: food9, price: "₦3,150", review: 4 },
    { id: 30, title: "Beef Burger", image: food9, price: "₦3,200", review: 3 },
  ],
};
