export const data = {
  pagination: {
    currentPage: 1, // can be dynamically updated
    pageSize: 6,
    total: 30, // total number of vehicles
  },
  vehicles: [
    { id: 1, status: "Not Started" },
    { id: 2, status: "Not Started" },
    { id: 3, status: "Not Started" },
    { id: 4, status: "Not Started" },
    { id: 5, status: "Not Started" },
    { id: 6, status: "Not Started" },
    { id: 7, status: "Not Started" },
    { id: 8, status: "Not Started" },
    { id: 9, status: "Not Started" },
    { id: 10, status: "Not Started" },
    { id: 11, status: "Not Started" },
    { id: 12, status: "Not Started" },
    { id: 13, status: "Not Started" },
    { id: 14, status: "Not Started" },
    { id: 15, status: "Not Started" },
    { id: 16, status: "In Progress" },
    { id: 17, status: "In Progress" },
    { id: 18, status: "Completed" },
    { id: 19, status: "Not Started" },
    { id: 20, status: "Not Started" },
    { id: 21, status: "Not Started" },
    { id: 22, status: "Not Started" },
    { id: 23, status: "Not Started" },
    { id: 24, status: "Not Started" },
    { id: 25, status: "Not Started" },
    { id: 26, status: "Not Started" },
    { id: 27, status: "Not Started" },
    { id: 28, status: "Not Started" },
    { id: 29, status: "Not Started" },
    { id: 30, status: "Not Started" },
  ],
};
