export const FETCH_FOOD_LOADING = "FETCH_FOOD_LOADING";
export const FETCH_FOOD_SUCCESS = "FETCH_FOOD_SUCCESS";
export const FETCH_FOOD_FAILED = "FETCH_FOOD_FAILED";
export const IS_FETCH_MORE = "IS_FETCH_MORE";
